import { User } from "./auth.models";
import { Product } from "./product.interface";

export interface Order {
  id?: number; // Optional because it's generated by the backend
  date: Date;
  status: string;
  user: User;
  products:Product[];

}
